### ISSUE TITLE
Flaky tests: Dataframe containing duplicated files is not properly saved

### ISSUE THREAD

**Issue by dpordomingo** [src-d/gemini#22] opened 2017-12-20 18:49 UTC
## Problem

tests sometimes fail with the following output.

## How to reproduce

Run `./sbt test` many times, and it'll fail sometimes. It is difficult to reproduce in the CI (because it takes more time), but I could see there that error a couple of times.

Using the tip of [dpordomingo/gemini::reproduce-issue-22](https://github.com/dpordomingo/gemini/tree/reproduce-issue-22), I created a gist with the 3 scenarios I found:

### Test succeeds
No data is stored in the `test_hashes_duplicates`
- [`report1-succeeding.txt`](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report1-succeeding-txt) -> output of the passing tests 
- [`report1-succeeding-db.txt`](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report1-succeeding-db-txt) -> content of the testing keyspaces. Both keyspaces are full of data

### Test fails
No data at all is stored in the `test_hashes_duplicates`
- [`report2-failing.txt`](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report2-failing-txt) -> output of the failing test
- [`report2-failing-db.txt`](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report2-failing-db-txt) -> content of the testing keyspaces. There is *no data* in `test_hashes_duplicates`

Partial data is stored in the `test_hashes_duplicates`
- [`report3-failing.txt`](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report3-failing-txt) -> output of the failing test
- [`report3-failing-db.txt`](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report3-failing-db-txt) -> content of the testing keyspaces. Only the half of the data retrieved by engine were saved in `test_hashes_duplicates` (the `srcd/borges` repo is hashed, but `erizocosmico/borges` repo is lost.

## More info

It requires more investigation, but it could be related when how data is stored during the tests before the test cases start running.

Currently, in the `beforeAll` section, it is created two keyspaces (`test_hashes_duplicates` for tests needing duplicates, `test_hashes_uniques` for tests needing no duplicates)
This is done in two stages:
1. engine returns a `DataFrame` containing all the files in the given siva files,
2. the `DataFrame` is stored in Cassandra <-- (I think something fails at this point) 

After the `beforeAll` the test cases run, and (sometimes) the ones asserting that there are duplicate files in `test_hashes_duplicates` fails.

It can be seen in the logs, that in all situations the `DataFrame` is populated with the right contents ([1](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report1-succeeding-txt-L252),[2](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report2-failing-txt-L252),[3](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report3-failing-txt-L252)).
But then:
- when no data is stored at all, at the `save` stage, there is always outputed `Wrote 0 rows to test_hashes_duplicates.blob_hash_files`
- when half of the data is stored, at the `save` stage, there is one row that says:  `Wrote 47 rows to test_hashes_duplicates.blob_hash_files` [47 rows](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report3-failing-txt-L288)
- when everything go well, at the `save` stage, there are some rows that say `Wrote n rows to test_hashes_duplicates.blob_hash_files`, and the sum of all rows sum `80` [33 rows](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report1-succeeding-txt-L272) +  [47 rows](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report1-succeeding-txt-L276)

## Hints

- Why when duplicate data is partially saved into `test_hashes_duplicates`, the missing files are from `github.com/erizocosmico/borges.git`? ([here](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report3-failing-db-txt))
- Why `DataFrame` is always populated with right data, but sometimes its data is not properly saved?

**Comment by smacker** [comment] 2017-12-26 16:31
should we close this one? Looks like everything was done in https://github.com/src-d/gemini/issues/20

**Comment by dpordomingo** [comment] 2017-12-26 23:10
I'm not sure that this issue is related with #20, that seems to be related with a bug with engine but this one seems to be related with the saving process.
Could you reproduce any of the described issues here before applying #26 , and couldn't they be reproduced after applying it?

**Comment by smacker** [comment] 2017-12-27 09:18
I couldn't reproduce this error using https://github.com/src-d/gemini/pull/26
That's why I suggested to close the issue.
But maybe I have to run tests more times?
How many times on average did you run tests to catch this error?

**Comment by dpordomingo** [comment] 2017-12-27 10:50
I didn't calculate the reproduction ratio, but based on the amount of time I spent trying to describe the bug I'd estimate a 1:5 ratio. If you was able to reproduce it before #26 (or with the tip of [dpordomingo/gemini:reproduce-issue-22](https://github.com/dpordomingo/gemini/tree/reproduce-issue-22)), but you couldn't reproduce it after #26, I'd close this issue.
If you weren't able to reproduce it at any point, it could be related with the OS so leave it open and I'll test it again once I'm back.

**Comment by smacker** [comment] 2017-12-27 11:53
yes. I had this problem before (but very-very rarely) and I don't have it now (at least for the last like 10-15-20 runs). Let's keep it open for now then if you think it can be still there. When you prove you don't have the issue anymore on your system we will close it.

**Comment by dpordomingo** [comment] 2017-12-27 16:19
Great. I'll assign myself the issue to review it asap.

**Comment by dpordomingo** [comment] 2018-01-02 14:34
From current `master` at 7753eef I got 11 errors during 50 test iterations.
With the code at #26 (engine v0.2) I got no errors during 50 test iterations, so this issue can be closed.

I ran the following:
```bash
exitCode=0;
iteration="1";
LOG="flakyTest.log";
echo -e "Running flaky tests...\n" | tee ${LOG};

while [ ${iteration} -lt 3 ]; do
    echo "[FlakyTest] RUNNING ITERATION n#${iteration}" | tee -a ${LOG};
    ./sbt test;
    exitCode=$?;
    echo "[FlakyTest] ... exited with code '${exitCode}'." | tee -a ${LOG};
    iteration=$[$iteration+1];
done

echo -e "\n\nREPORT:\n----------";
cat ${LOG_SHORT};
```

**Comment by dpordomingo** [comment] 2018-01-02 14:35
The PR #26  that solves this issue is pending approval, so I reopened and linked there this issue

**Closed** 2018-01-02 18:02 UTC
Labels: bug
