### ISSUE TITLE
Fix WARN on ./report

### ISSUE THREAD

**Issue by bzz** [src-d/gemini#102] opened 2018-04-19 09:59 UTC
Right now, after https://github.com/src-d/gemini/pull/90#issuecomment-382173900 `./report` command (at least on macOS) produces

```
WARN 11:57:50 org.apache.hadoop.fs.FileSystem$Statistics$StatisticsDataReferenceCleaner (FileSystem.java:2995) - exception in the cleaner thread but it will continue to run
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at org.apache.hadoop.fs.FileSystem$Statistics$StatisticsDataReferenceCleaner.run(FileSystem.java:2989)
	at java.lang.Thread.run(Thread.java:748)
```

It is may or may not be related to [HADOOP-12829](https://issues.apache.org/jira/browse/HADOOP-12829) - the goal is to find out and fix it.

**Comment by bzz** [comment] 2018-04-19 15:49
@carlosms this is also [reproducible on CI](https://travis-ci.org/src-d/gemini/jobs/368709099#L2073)

**Comment by carlosms** [comment] 2018-04-19 16:15
:+1: thanks for opening an issue for this.

**Comment by smacker** [comment] 2018-05-04 15:33
Can't reproduce locally on #111. Also there is no warning in CI anymore: https://travis-ci.org/src-d/gemini/jobs/374500799#L1423

closing.

**Closed by smacker** 2018-05-04 15:33 UTC
Labels: bug
